version: "3"
volumes:
   pgdata:
services:
   pagila:
      image: postgres:17.5
      container_name: pagila
      environment:
         POSTGRES_USER: javosw
         POSTGRES_PASSWORD: 122333
         POSTGRES_DB: pagila
      volumes:
         - ./sql/main/pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
         - ./sql/main/pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
         - pgdata:/var/lib/postgresql/data
      expose:
         - 5432
      ports:
         - 5401:5432
   pgadmin:
      container_name: pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
         PGADMIN_DEFAULT_EMAIL: admin@admin.com
         PGADMIN_DEFAULT_PASSWORD: 122333
      ports:
         - "5402:80"
